In [1]:
from sklearn import svm , datasets
d=datasets.load_iris()

In [2]:
import pandas as pd
df=pd.DataFrame(d.data,columns=d.feature_names)
df['flower']=d.target
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),flower
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [3]:
from sklearn.model_selection import train_test_split
j_train,j_test,h_train,h_test= train_test_split(d.data,d.target,test_size=0.2)

In [4]:
model=svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(j_train,h_train)
model.score(j_test,h_test)

0.9333333333333333

### grid searchCV

In [5]:
from sklearn.model_selection import GridSearchCV as gcv

clf=gcv(svm.SVC(gamma='auto'),{
    'C':[1,10,20,50],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

clf.fit(d.data,d.target)
clf.cv_results_

{'mean_fit_time': array([0.00114636, 0.00077367, 0.0016665 , 0.00158448, 0.00154061,
        0.00146651, 0.        , 0.00165873]),
 'std_fit_time': array([0.00229273, 0.00154734, 0.003333  , 0.00316896, 0.00308123,
        0.00293303, 0.        , 0.00331745]),
 'mean_score_time': array([9.66262817e-04, 0.00000000e+00, 0.00000000e+00, 1.59883499e-04,
        8.54492187e-05, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 'std_score_time': array([0.00193253, 0.        , 0.        , 0.00031977, 0.0001709 ,
        0.        , 0.        , 0.        ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 50, 50],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 50, 'kernel': 'rbf'},
  {'C': 50, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 1.        , 1.        ]),
 'split1_test_score': array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 0.96666667, 1.        ]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96666667]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.0421637 ]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 8, 6])}

In [6]:
df=pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001146,0.002293,0.000966,0.001933,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.000774,0.001547,0.000000,0.000000,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.001666,0.003333,0.000000,0.000000,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001584,0.003169,0.000160,0.000320,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.001541,0.003081,0.000085,0.000171,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.001467,0.002933,0.000000,0.000000,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.000000,0.000000,0.000000,0.000000,50,rbf,"{'C': 50, 'kernel': 'rbf'}",1.000000,0.966667,0.900000,0.933333,1.0,0.960000,0.038873,8
7,0.001659,0.003317,0.000000,0.000000,50,linear,"{'C': 50, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6

In [7]:
df[['param_C','param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667
6      50          rbf         0.960000
7      50       linear         0.966667

In [8]:
#dir(clf)  use when needed important to know what the values you can get !

In [9]:
# Randomized searchCV

In [10]:
from sklearn.model_selection import RandomizedSearchCV as rcv

rs=rcv(svm.SVC(gamma='auto'),{
    'C':[1,10,20,50],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False,n_iter=2)

rs.fit(d.data,d.target)
rs.cv_results_

pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1      20          rbf         0.966667

In [11]:
# hyperparameter tunnning

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [13]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

# Define hyperparameters for each model
svc_params = {
    'C': [0.1, 1, 10],  
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto'],
    'degree': [3, 4, 5]
}

rf_params = {
    'n_estimators': [100, 300, 500],  
    'max_depth': [None, 10, 20],  
    'min_samples_split': [2, 5, 10],  
    'min_samples_leaf': [1, 2, 4],  
    'bootstrap': [True, False]  
}

logreg_params = {
    'penalty': ['l1', 'l2'],  
    'C': [0.001, 0.01, 0.1, 1, 10, 100],  
    'solver': ['liblinear'],  
    'max_iter': [100, 200, 300]  
}

# Combine into a single dictionary
model_params = {
    'SVC': {'model': SVC(), 'params': svc_params},
    'RandomForestClassifier': {'model': RandomForestClassifier(), 'params': rf_params},
    'LogisticRegression': {'model': LogisticRegression(), 'params': logreg_params}
}

# Print combined dictionary
print(model_params)

{'SVC': {'model': SVC(), 'params': {'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf'], 'gamma': ['scale', 'auto'], 'degree': [3, 4, 5]}}, 'RandomForestClassifier': {'model': RandomForestClassifier(), 'params': {'n_estimators': [100, 300, 500], 'max_depth': [None, 10, 20], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4], 'bootstrap': [True, False]}}, 'LogisticRegression': {'model': LogisticRegression(), 'params': {'penalty': ['l1', 'l2'], 'C': [0.001, 0.01, 0.1, 1, 10, 100], 'solver': ['liblinear'], 'max_iter': [100, 200, 300]}}}

In [16]:
for mod, mp in model_params.items():
    cl = gcv(mp['model'], mp['params'], cv=5, return_train_score=False)
    cl.fit(d.data, d.target)
    scores.append({
        'model': mod,
        'best_score': cl.best_score_,
        'best_params': cl.best_params_
    })

print(scores)

NameError: name 'scores' is not defined

In [ ]:
df=pd.DataFrame(scores,columns=['model','best_score','best params'])

In [ ]:
df